# Generated by Django 3.1.5 on 2021-01-13 10:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetail',
            name='transactionOn',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 13, 10, 2, 35, 855608, tzinfo=utc)),
        ),
    ]
